name: Bans
version: '${version}'
author: kgm
main: io.bans.plugin.BukkitPlugin
description: A free solution designed to help you track your Minecraft bans, warnings, and other related information.
website: https://bans.io
commands:
  bans:
    description: The base plugin command.
  ban:
    description: Bans a player.
  unban:
    description: Unbans a player.
  warn:
    description: Warns a player.
  mute:
    description: Mutes a player.
  unmute:
    description: Unmutes a player.
  kick:
    description: Kicks a player.
  kickall:
    description: Kicks all players.
  history:
    description: Shows a player's history.
  check:
    description: Checks a player's status.
